/*
-- Query: 
-- Date: 2014-02-18 16:46
*/
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (1,NULL,'Categoria Padre',NULL,NULL,NULL,NULL,NULL,1,1,1);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (2,NULL,'Arte',NULL,NULL,NULL,NULL,NULL,1,2,1);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (3,NULL,'Automoviles',NULL,NULL,NULL,NULL,NULL,1,2,3);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (4,NULL,'Belleza',NULL,NULL,NULL,NULL,NULL,1,2,1);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (5,NULL,'Libros',NULL,NULL,NULL,NULL,NULL,1,2,3);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (6,NULL,'Celulares & Accesorios',NULL,NULL,NULL,NULL,NULL,1,2,1);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (7,NULL,'Vestimenta',NULL,NULL,NULL,NULL,NULL,1,2,1);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (8,NULL,'Computadoras',NULL,NULL,NULL,NULL,NULL,1,2,3);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (9,NULL,'Electronica',NULL,NULL,NULL,NULL,NULL,1,2,3);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (10,NULL,'Salud',NULL,NULL,NULL,NULL,NULL,1,2,2);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (11,NULL,'Casa & Cocina',NULL,NULL,NULL,NULL,NULL,1,2,1);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (12,NULL,'Joyeria',NULL,NULL,NULL,NULL,NULL,1,2,2);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (13,NULL,'Instrumentos Musicales',NULL,NULL,NULL,NULL,NULL,1,2,1);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (14,NULL,'Productos De Oficina',NULL,NULL,NULL,NULL,NULL,1,2,1);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (15,NULL,'Sumplementos De Mascotas',NULL,NULL,NULL,NULL,NULL,1,2,1);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (16,NULL,'Zapatos',NULL,NULL,NULL,NULL,NULL,1,2,2);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (17,NULL,'Deportes',NULL,NULL,NULL,NULL,NULL,1,2,1);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (18,NULL,'Video Juegos',NULL,NULL,NULL,NULL,NULL,1,2,2);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (19,NULL,'Relojeria',NULL,NULL,NULL,NULL,NULL,1,2,2);
