/*
-- Query: 
-- Date: 2014-02-16 20:42
*/
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (1,'TGU','Tegucigalpa',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (2,'SPS','San Pedro Sula',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (3,'CEI','La Ceiba',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (4,'CHO','Choluteca',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (5,'DAN','Danli',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (6,'SRS','Santa Rosa de Copan',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (7,'COM','Comayagua',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (8,'CAT','Catacamas',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (9,'JUT','Juticalpa',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (10,'SIG','Siguatepeque',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (11,'PRO','El Progreso',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (12,'PCO','Puerto Cortes',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (13,'OMO','Omoa',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (14,'TRU','Trujillo',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (15,'TOC','Tocoa',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (16,'LES','La Esperanza',NULL,NULL,NULL,NULL,NULL);
