/*
-- Query: 
-- Date: 2014-02-27 18:31
*/

INSERT INTO `CON_ClasificacionCuenta` (`CON_ClasificacionCuenta_ID`,`CON_ClasificacionCuenta_Nombre`,`CON_ClasificacionCuenta_FechaCreacion`,`CON_ClasificacionCuenta_FechaModificacion`,`CON_ClasificacionCuenta_Categoria`,`CON_ClasificacionCuenta_Subcategoria`) VALUES (1,'Activo Corriente','03-03-03',Now(),'1','10');
INSERT INTO `CON_ClasificacionCuenta` (`CON_ClasificacionCuenta_ID`,`CON_ClasificacionCuenta_Nombre`,`CON_ClasificacionCuenta_FechaCreacion`,`CON_ClasificacionCuenta_FechaModificacion`,`CON_ClasificacionCuenta_Categoria`,`CON_ClasificacionCuenta_Subcategoria`) VALUES (2,'Propiedad Planta y Equipo','03-03-03',Now(),'1','21');
INSERT INTO `CON_ClasificacionCuenta` (`CON_ClasificacionCuenta_ID`,`CON_ClasificacionCuenta_Nombre`,`CON_ClasificacionCuenta_FechaCreacion`,`CON_ClasificacionCuenta_FechaModificacion`,`CON_ClasificacionCuenta_Categoria`,`CON_ClasificacionCuenta_Subcategoria`) VALUES (3,'Activos Intangibles','03-03-03',Now(),'1','22');
INSERT INTO `CON_ClasificacionCuenta` (`CON_ClasificacionCuenta_ID`,`CON_ClasificacionCuenta_Nombre`,`CON_ClasificacionCuenta_FechaCreacion`,`CON_ClasificacionCuenta_FechaModificacion`,`CON_ClasificacionCuenta_Categoria`,`CON_ClasificacionCuenta_Subcategoria`) VALUES (4,'Pasivos Corrientes','03-03-03',Now(),'2','10');
INSERT INTO `CON_ClasificacionCuenta` (`CON_ClasificacionCuenta_ID`,`CON_ClasificacionCuenta_Nombre`,`CON_ClasificacionCuenta_FechaCreacion`,`CON_ClasificacionCuenta_FechaModificacion`,`CON_ClasificacionCuenta_Categoria`,`CON_ClasificacionCuenta_Subcategoria`) VALUES (5,'Pasivos no Corrientes','03-03-03',Now(),'2','20');
INSERT INTO `CON_ClasificacionCuenta` (`CON_ClasificacionCuenta_ID`,`CON_ClasificacionCuenta_Nombre`,`CON_ClasificacionCuenta_FechaCreacion`,`CON_ClasificacionCuenta_FechaModificacion`,`CON_ClasificacionCuenta_Categoria`,`CON_ClasificacionCuenta_Subcategoria`) VALUES (6,'Capital Contable/Patrimonio: Comerciante Individual','03-03-03',Now(),'3','01');
INSERT INTO `CON_ClasificacionCuenta` (`CON_ClasificacionCuenta_ID`,`CON_ClasificacionCuenta_Nombre`,`CON_ClasificacionCuenta_FechaCreacion`,`CON_ClasificacionCuenta_FechaModificacion`,`CON_ClasificacionCuenta_Categoria`,`CON_ClasificacionCuenta_Subcategoria`) VALUES (7,'Capital Contable/Patrimonio: Empresa Jurídica','03-03-03',Now(),'3','02');
INSERT INTO `CON_ClasificacionCuenta` (`CON_ClasificacionCuenta_ID`,`CON_ClasificacionCuenta_Nombre`,`CON_ClasificacionCuenta_FechaCreacion`,`CON_ClasificacionCuenta_FechaModificacion`,`CON_ClasificacionCuenta_Categoria`,`CON_ClasificacionCuenta_Subcategoria`) VALUES (8,'Ingresos','03-03-03',Now(),'4','00');
INSERT INTO `CON_ClasificacionCuenta` (`CON_ClasificacionCuenta_ID`,`CON_ClasificacionCuenta_Nombre`,`CON_ClasificacionCuenta_FechaCreacion`,`CON_ClasificacionCuenta_FechaModificacion`,`CON_ClasificacionCuenta_Categoria`,`CON_ClasificacionCuenta_Subcategoria`) VALUES (9,'Gastos','03-03-03',Now(),'5','00');