/*
-- Query: select * FROM pymeERP.INV_Proveedor
-- Date: 2014-03-20 15:11
*/
INSERT INTO `INV_Proveedor` (`INV_Proveedor_ID`,`INV_Proveedor_Codigo`,`INV_Proveedor_Nombre`,`INV_Proveedor_Direccion`,`INV_Proveedor_Telefono`,`INV_Proveedor_Email`,`INV_Proveedor_PaginaWeb`,`INV_Proveedor_RepresentanteVentas`,`INV_Proveedor_TelefonoRepresentanteVentas`,`INV_Proveedor_Comentarios`,`INV_Proveedor_RutaImagen`,`INV_Proveedor_FechaCreacion`,`INV_Proveedor_UsuarioCreacion`,`INV_Proveedor_FechaModificacion`,`INV_Proveedor_UsuarioModificacion`,`INV_Proveedor_Activo`,`INV_Ciudad_ID`) VALUES (1,'PROV-0001','Cerveceria','Tramo que conduce a Metro Mall.','(504)2226-7117','cerveceria@gmail.com','www.cerveceria.hn','Juan Perez','(504)9992-1645','','',now(),substring_index(user(),'@',1),now(),substring_index(user(),'@',1),1,2);
INSERT INTO `INV_Proveedor` (`INV_Proveedor_ID`,`INV_Proveedor_Codigo`,`INV_Proveedor_Nombre`,`INV_Proveedor_Direccion`,`INV_Proveedor_Telefono`,`INV_Proveedor_Email`,`INV_Proveedor_PaginaWeb`,`INV_Proveedor_RepresentanteVentas`,`INV_Proveedor_TelefonoRepresentanteVentas`,`INV_Proveedor_Comentarios`,`INV_Proveedor_RutaImagen`,`INV_Proveedor_FechaCreacion`,`INV_Proveedor_UsuarioCreacion`,`INV_Proveedor_FechaModificacion`,`INV_Proveedor_UsuarioModificacion`,`INV_Proveedor_Activo`,`INV_Ciudad_ID`) VALUES (2,'PROV-0002','Walmart','Dentro del Mall Las Casacadas.','(504)2221-5478','walmart@yahoo.com','www.walmart.hn','Miguel Cruz','(504)9994-2114','','',now(),substring_index(user(),'@',1),now(),substring_index(user(),'@',1),1,1);
INSERT INTO `INV_Proveedor` (`INV_Proveedor_ID`,`INV_Proveedor_Codigo`,`INV_Proveedor_Nombre`,`INV_Proveedor_Direccion`,`INV_Proveedor_Telefono`,`INV_Proveedor_Email`,`INV_Proveedor_PaginaWeb`,`INV_Proveedor_RepresentanteVentas`,`INV_Proveedor_TelefonoRepresentanteVentas`,`INV_Proveedor_Comentarios`,`INV_Proveedor_RutaImagen`,`INV_Proveedor_FechaCreacion`,`INV_Proveedor_UsuarioCreacion`,`INV_Proveedor_FechaModificacion`,`INV_Proveedor_UsuarioModificacion`,`INV_Proveedor_Activo`,`INV_Ciudad_ID`) VALUES (3,'PROV-0003','La Colonia','Frente a City Mall.','(504)2223-8745','lacolonia@msn.com','www.lacolonia.hn','Hugo Boss','(504)9874-6231','','',now(),substring_index(user(),'@',1),now(),substring_index(user(),'@',1),1,4);
INSERT INTO `INV_Proveedor` (`INV_Proveedor_ID`,`INV_Proveedor_Codigo`,`INV_Proveedor_Nombre`,`INV_Proveedor_Direccion`,`INV_Proveedor_Telefono`,`INV_Proveedor_Email`,`INV_Proveedor_PaginaWeb`,`INV_Proveedor_RepresentanteVentas`,`INV_Proveedor_TelefonoRepresentanteVentas`,`INV_Proveedor_Comentarios`,`INV_Proveedor_RutaImagen`,`INV_Proveedor_FechaCreacion`,`INV_Proveedor_UsuarioCreacion`,`INV_Proveedor_FechaModificacion`,`INV_Proveedor_UsuarioModificacion`,`INV_Proveedor_Activo`,`INV_Ciudad_ID`) VALUES (4,'PROV-0004','Pricesmart','Frente a Mall Multiplaza.','(504)2212-9654','pricesmart@gmail.com','www.pricesmart.com','Daniel Carias','(504)9978-1295','','',now(),substring_index(user(),'@',1),now(),substring_index(user(),'@',1),1,3);
INSERT INTO `INV_Proveedor` (`INV_Proveedor_ID`,`INV_Proveedor_Codigo`,`INV_Proveedor_Nombre`,`INV_Proveedor_Direccion`,`INV_Proveedor_Telefono`,`INV_Proveedor_Email`,`INV_Proveedor_PaginaWeb`,`INV_Proveedor_RepresentanteVentas`,`INV_Proveedor_TelefonoRepresentanteVentas`,`INV_Proveedor_Comentarios`,`INV_Proveedor_RutaImagen`,`INV_Proveedor_FechaCreacion`,`INV_Proveedor_UsuarioCreacion`,`INV_Proveedor_FechaModificacion`,`INV_Proveedor_UsuarioModificacion`,`INV_Proveedor_Activo`,`INV_Ciudad_ID`) VALUES (5,'PROV-0005','Hyper Paiz','Frente a la Llantera','(504)2214-7896','hyperpaiz@gmail.com','www.hyperpaiz.com','Guillermo Paz','(504)9987-4512','','',now(),substring_index(user(),'@',1),now(),substring_index(user(),'@',1),1,7);
