/*
-- Query: 
-- Date: 2014-02-16 20:42
*/
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (1,'TGU','Tegucigalpa',now(),'Administrador',now(),'Administrador','1');
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (2,'SPS','San Pedro Sula',now(),'Administrador',now(),'Administrador','1');
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (3,'CEI','La Ceiba',now(),'Administrador',now(),'Administrador','1');
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (4,'CHO','Choluteca',now(),'Administrador',now(),'Administrador','1');
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (5,'DAN','Danli',now(),'Administrador',now(),'Administrador','1');
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (6,'SRS','Santa Rosa de Copan',now(),'Administrador',now(),'Administrador','1');
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (7,'COM','Comayagua',now(),'Administrador',now(),'Administrador','1');
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (8,'CAT','Catacamas',now(),'Administrador',now(),'Administrador','1');
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (9,'JUT','Juticalpa',now(),'Administrador',now(),'Administrador','1');
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (10,'SIG','Siguatepeque',now(),'Administrador',now(),'Administrador','1');
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (11,'PRO','El Progreso',now(),'Administrador',now(),'Administrador','1');
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (12,'PCO','Puerto Cortes',now(),'Administrador',now(),'Administrador','1');
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (13,'OMO','Omoa',now(),'Administrador',now(),'Administrador','1');
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (14,'TRU','Trujillo',now(),'Administrador',now(),'Administrador','1');
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (15,'TOC','Tocoa',now(),'Administrador',now(),'Administrador','1');
INSERT INTO `INV_Ciudad` (`INV_Ciudad_ID`,`INV_Ciudad_Codigo`,`INV_Ciudad_Nombre`,`INV_Ciudad_FechaCreacion`,`INV_Ciudad_UsuarioCreacion`,`INV_Ciudad_FechaModificacion`,`INV_Ciudad_UsuarioModificacion`,`INV_Ciudad_Activo`) VALUES (16,'LES','La Esperanza',now(),'Administrador',now(),'Administrador','1');
