/*
-- Query: 
-- Date: 2014-02-16 21:15
*/
INSERT INTO `INV_Atributo` (`INV_Atributo_ID`,`INV_Atributo_Codigo`,`INV_Atributo_Nombre`,`INV_Atributo_TipoDato`,`INV_Atributo_FechaCreacion`,`INV_Atributo_UsuarioCreacion`,`INV_Atributo_FechaModificacion`,`INV_Atributo_UsuarioModificacion`,`INV_Atributo_Activo`) VALUES (1,NULL,'Color',NULL,now(),'Administrador',now(),'Administrador','1');
INSERT INTO `INV_Atributo` (`INV_Atributo_ID`,`INV_Atributo_Codigo`,`INV_Atributo_Nombre`,`INV_Atributo_TipoDato`,`INV_Atributo_FechaCreacion`,`INV_Atributo_UsuarioCreacion`,`INV_Atributo_FechaModificacion`,`INV_Atributo_UsuarioModificacion`,`INV_Atributo_Activo`) VALUES (2,NULL,'Bateria',NULL,now(),'Administrador',now(),'Administrador','1');
INSERT INTO `INV_Atributo` (`INV_Atributo_ID`,`INV_Atributo_Codigo`,`INV_Atributo_Nombre`,`INV_Atributo_TipoDato`,`INV_Atributo_FechaCreacion`,`INV_Atributo_UsuarioCreacion`,`INV_Atributo_FechaModificacion`,`INV_Atributo_UsuarioModificacion`,`INV_Atributo_Activo`) VALUES (3,NULL,'Peso',NULL,now(),'Administrador',now(),'Administrador','1');
INSERT INTO `INV_Atributo` (`INV_Atributo_ID`,`INV_Atributo_Codigo`,`INV_Atributo_Nombre`,`INV_Atributo_TipoDato`,`INV_Atributo_FechaCreacion`,`INV_Atributo_UsuarioCreacion`,`INV_Atributo_FechaModificacion`,`INV_Atributo_UsuarioModificacion`,`INV_Atributo_Activo`) VALUES (4,NULL,'Dimensiones',NULL,now(),'Administrador',now(),'Administrador','1');
INSERT INTO `INV_Atributo` (`INV_Atributo_ID`,`INV_Atributo_Codigo`,`INV_Atributo_Nombre`,`INV_Atributo_TipoDato`,`INV_Atributo_FechaCreacion`,`INV_Atributo_UsuarioCreacion`,`INV_Atributo_FechaModificacion`,`INV_Atributo_UsuarioModificacion`,`INV_Atributo_Activo`) VALUES (5,NULL,'Unidades',NULL,now(),'Administrador',now(),'Administrador','1');
INSERT INTO `INV_Atributo` (`INV_Atributo_ID`,`INV_Atributo_Codigo`,`INV_Atributo_Nombre`,`INV_Atributo_TipoDato`,`INV_Atributo_FechaCreacion`,`INV_Atributo_UsuarioCreacion`,`INV_Atributo_FechaModificacion`,`INV_Atributo_UsuarioModificacion`,`INV_Atributo_Activo`) VALUES (6,NULL,'Fragancia',NULL,now(),'Administrador',now(),'Administrador','1');
INSERT INTO `INV_Atributo` (`INV_Atributo_ID`,`INV_Atributo_Codigo`,`INV_Atributo_Nombre`,`INV_Atributo_TipoDato`,`INV_Atributo_FechaCreacion`,`INV_Atributo_UsuarioCreacion`,`INV_Atributo_FechaModificacion`,`INV_Atributo_UsuarioModificacion`,`INV_Atributo_Activo`) VALUES (7,NULL,'Material',NULL,now(),'Administrador',now(),'Administrador','1');
INSERT INTO `INV_Atributo` (`INV_Atributo_ID`,`INV_Atributo_Codigo`,`INV_Atributo_Nombre`,`INV_Atributo_TipoDato`,`INV_Atributo_FechaCreacion`,`INV_Atributo_UsuarioCreacion`,`INV_Atributo_FechaModificacion`,`INV_Atributo_UsuarioModificacion`,`INV_Atributo_Activo`) VALUES (8,NULL,'Pantalla',NULL,now(),'Administrador',now(),'Administrador','1');
INSERT INTO `INV_Atributo` (`INV_Atributo_ID`,`INV_Atributo_Codigo`,`INV_Atributo_Nombre`,`INV_Atributo_TipoDato`,`INV_Atributo_FechaCreacion`,`INV_Atributo_UsuarioCreacion`,`INV_Atributo_FechaModificacion`,`INV_Atributo_UsuarioModificacion`,`INV_Atributo_Activo`) VALUES (9,NULL,'Fabricante',NULL,now(),'Administrador',now(),'Administrador','1');
INSERT INTO `INV_Atributo` (`INV_Atributo_ID`,`INV_Atributo_Codigo`,`INV_Atributo_Nombre`,`INV_Atributo_TipoDato`,`INV_Atributo_FechaCreacion`,`INV_Atributo_UsuarioCreacion`,`INV_Atributo_FechaModificacion`,`INV_Atributo_UsuarioModificacion`,`INV_Atributo_Activo`) VALUES (10,NULL,'Editorial',NULL,now(),'Administrador',now(),'Administrador','1');
