/*
-- Query: 
-- Date: 2014-02-18 16:46
*/
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (0,NULL,'Categoría Padre',NULL,NULL,NULL,NULL,NULL,NULL,0,1);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (1,NULL,'Arte',NULL,NULL,NULL,NULL,NULL,NULL,1,1);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (2,NULL,'Automoviles',NULL,NULL,NULL,NULL,NULL,NULL,1,3);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (3,NULL,'Belleza',NULL,NULL,NULL,NULL,NULL,NULL,1,1);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (4,NULL,'Libros',NULL,NULL,NULL,NULL,NULL,NULL,1,3);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (5,NULL,'Celulares & Accesorios',NULL,NULL,NULL,NULL,NULL,NULL,1,1);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (6,NULL,'Vestimenta',NULL,NULL,NULL,NULL,NULL,NULL,1,1);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (7,NULL,'Computadoras',NULL,NULL,NULL,NULL,NULL,NULL,1,3);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (8,NULL,'Electronica',NULL,NULL,NULL,NULL,NULL,NULL,1,3);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (9,NULL,'Salud',NULL,NULL,NULL,NULL,NULL,NULL,1,2);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (10,NULL,'Casa & Cocina',NULL,NULL,NULL,NULL,NULL,NULL,1,1);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (11,NULL,'Joyeria',NULL,NULL,NULL,NULL,NULL,NULL,1,2);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (12,NULL,'Instrumentos Musicales',NULL,NULL,NULL,NULL,NULL,NULL,1,1);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (13,NULL,'Productos De Oficina',NULL,NULL,NULL,NULL,NULL,NULL,1,1);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (14,NULL,'Sumplementos De Mascotas',NULL,NULL,NULL,NULL,NULL,NULL,1,1);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (15,NULL,'Zapatos',NULL,NULL,NULL,NULL,NULL,NULL,1,2);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (16,NULL,'Deportes',NULL,NULL,NULL,NULL,NULL,NULL,1,1);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (17,NULL,'Video Juegos',NULL,NULL,NULL,NULL,NULL,NULL,1,2);
INSERT INTO `INV_Categoria` (`INV_Categoria_ID`,`INV_Categoria_Codigo`,`INV_Categoria_Nombre`,`INV_Categoria_Descripcion`,`INV_Categoria_FechaCreacion`,`INV_Categoria_UsuarioCreacion`,`INV_Categoria_FechaModificacion`,`INV_Categoria_UsuarioModificacion`,`INV_Categoria_Activo`,`INV_Categoria_IDCategoriaPadre`,`INV_Categoria_HorarioDescuento_ID`) VALUES (18,NULL,'Relojeria',NULL,NULL,NULL,NULL,NULL,NULL,1,2);
